import { GetStaticProps } from "next";
import Head from "next/head";
import { Layout } from "../components/Layout";
import Main from "../components/main/Main";

export default function Home() {
  return (
    <>
      <Layout>
        <Head>
          <title>minsan todo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Main />
      </Layout>
    </>
  );
}
